version: '3.9'

services:
   zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0  # Use Confluent's Zookeeper image
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network
   kafka:
    image: confluentinc/cp-kafka:7.3.0  # Use Confluent's Kafka image
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-network

   postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    networks:
      - kafka-network

   kafka_producer:
    build: ./kafka_producer
    depends_on:
      - kafka
    networks:
      - kafka-network

   flink_processor:
    build: ./flink_processor
    depends_on:
      - kafka
      - postgres
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
